var i;
i = 3;
;
;
var button1$_web;
var button1$text;
var button1;
$('body').append("<button type='button' id='button1'></button>");
button1$text = 'Button from xaller.';
$('#button1').html('Button from xaller.');
button1$_web = 'Button';
button1$text = foo(bar(3, 2), bar(5, 6));
i = j = i = j = i = j = ;
$('#button1').html('t');
